export const InterlisGlspTypes = {
  diagramType: "interlis-class-diagram",
  classNodeType: "node:interlis-class",
  structureNodeType: "node:interlis-structure",
  viewNodeType: "node:interlis-view",
  enumerationNodeType: "node:interlis-enumeration",
  headerCompartmentType: "comp:interlis-header",
  attributeCompartmentType: "comp:interlis-attributes",
  constraintCompartmentType: "comp:interlis-constraints",
  namespaceLabelType: "label:interlis-namespace",
  stereotypeLabelType: "label:interlis-stereotype",
  nameLabelType: "label:interlis-name",
  attributeLabelType: "label:interlis-attribute",
  constraintLabelType: "label:interlis-constraint",
  associationLabelType: "label:interlis-association",
  inheritanceEdgeType: "edge:interlis-inheritance",
  associationEdgeType: "edge:interlis-association",
  cssClassNode: "interlis-node",
  cssClassClass: "interlis-class",
  cssClassStructure: "interlis-structure",
  cssClassView: "interlis-view",
  cssClassEnumeration: "interlis-enumeration",
  cssClassNamespace: "interlis-namespace",
  cssClassStereotype: "interlis-stereotype",
  cssClassName: "interlis-name",
  cssClassAttribute: "interlis-attribute",
  cssClassConstraint: "interlis-constraint",
  cssClassCompartment: "interlis-compartment",
  cssClassHeader: "interlis-header",
  cssClassAttributeCompartment: "interlis-attribute-compartment",
  cssClassConstraintCompartment: "interlis-constraint-compartment",
  cssClassAssociationLabel: "interlis-association-label",
  cssClassInheritanceEdge: "interlis-inheritance-edge",
  cssClassAssociationEdge: "interlis-association-edge",
  cssClassEnumLiteral: "interlis-enum-literal"
} as const;

export type InterlisGlspTypeKey = keyof typeof InterlisGlspTypes;
