export const InterlisGlspTypes = {
  diagramType: "interlis-class-diagram",
  topicNodeType: "node:interlis-topic",
  classNodeType: "node:interlis-class",
  structureNodeType: "node:interlis-structure",
  viewNodeType: "node:interlis-view",
  enumerationNodeType: "node:interlis-enumeration",
  topicHeaderType: "comp:interlis-topic-header",
  topicContentCompartmentType: "comp:interlis-topic-content",
  headerCompartmentType: "comp:interlis-header",
  bodyCompartmentType: "comp:interlis-body",
  attributeCompartmentType: "comp:interlis-attributes",
  constraintCompartmentType: "comp:interlis-constraints",
  enumerationLiteralCompartmentType: "comp:interlis-enumeration-literals",
  topicLabelType: "label:interlis-topic",
  nameLabelType: "label:interlis-name",
  stereotypeLabelType: "label:interlis-stereotype",
  attributeLabelType: "label:interlis-attribute",
  constraintLabelType: "label:interlis-constraint",
  enumerationLiteralLabelType: "label:interlis-enumeration-literal",
  cssTopicNode: "interlis-topic",
  cssClassNode: "interlis-class",
  cssStructureNode: "interlis-structure",
  cssViewNode: "interlis-view",
  cssEnumerationNode: "interlis-enumeration",
  cssTopicHeader: "interlis-topic-header",
  cssTopicContent: "interlis-topic-content",
  cssHeaderCompartment: "interlis-header",
  cssBodyCompartment: "interlis-body",
  cssAttributesCompartment: "interlis-attributes",
  cssConstraintsCompartment: "interlis-constraints",
  cssEnumerationLiteralsCompartment: "interlis-enumeration-literals",
  cssTopicLabel: "interlis-topic-label",
  cssStereotypeLabel: "interlis-stereotype-label",
  cssNameLabel: "interlis-name-label",
  cssAttributeLabel: "interlis-attribute-label",
  cssConstraintLabel: "interlis-constraint-label",
  cssEnumerationLiteralLabel: "interlis-enumeration-literal-label"
} as const;

export type InterlisGlspTypeKey = keyof typeof InterlisGlspTypes;
